### ISSUE TITLE
Accounting for multiple clicks by a single user on the same object?

### ISSUE THREAD

**Issue by cpadavis** [cpadavis/strongcnn#19]
Users can click more than one time. I have a minimum threshold of number of markers to be considered a cluster. If a user clicks on a cluster multiple times (say, more than that minimum threshold), then that one person has effectively forced that cutout into my system. The whole point of having a minimum number of markers was to leverage the opinion of many / overcome accidental clicks. I don't think I can modify the clustering algorithm to account for this, although I suppose I could weight each user by the number of clicks they made (each click dilutes the vote of an individual click?) and their skill.

Of course, if this is not a real issue, then I just close this and solve an issue for only the cost of a few minutes thought!

**Comment by drphilmarshall** [comment]
The thing you suppose sounds sensible. And might clean up the clustering
results too. Is it hard to implement?

**Comment by cpadavis** [comment]
for some reason I thought sklearn's version of dbscan (what I'm currently
using) had weights. (It doesn't.) It looks like in order to do any sort of
weight modification I'd have to modify the sklearn code a bit. I think it's
quite possible, if a little annoying. It actually should just be a two line
change in the sklearn/cluster/dbscan_.py: one for adding weights as a
possible input, and another for checking the min_samples (maybe a couple if
it is hard to go from neighbors to the right indices for weights).

**Comment by cpadavis** [comment]
just kidding upgrading sklearn from 0.15 to 0.16 gives me weights in
dbscan. Guess this was something many folks wanted. (There goes an obvious
chance to contribute to sklearn!)

**Comment by cpadavis** [comment]
done a little while back
