### ISSUE TITLE
get access to galzoo code

### ISSUE THREAD

**Issue by cpadavis** [cpadavis/strongcnn#20]
For moving this project forward and testing the transfer learning stuff, we should make sure everyone has access to the same galaxy zoo morphology training / testing sets. I think @rkeisler is best set to point us to this?

**Comment by rkeisler** [comment]
To access the Galaxy Zoo morphology training (and testing) data:
- Get an account on www.kaggle.com .
- Log into your kaggle account.
- Download relevant data from https://www.kaggle.com/c/galaxy-zoo-the-galaxy-challenge/data .

**Comment by cpadavis** [comment]
downloading!
